name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write       # allow the deploy step
  id-token: write    # for OpenID Connect with Pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install Node first (caches work better)
      - uses: actions/setup-node@v4
        with:
          node-version: 20          # any LTS you like
          cache: 'pnpm'
      # Install the exact pnpm version declared in package.json
      - uses: pnpm/action-setup@v4
        with:
          run_install: true         # runs 'pnpm install' for you
      - run: pnpm run build        # → dist/
      - uses: actions/upload-pages-artifact@v3
        with: { path: dist }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
