name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 · Check out code
      - uses: actions/checkout@v4

      # 2 · Install pnpm (adds it to PATH)
      - uses: pnpm/action-setup@v4          # docs: https://github.com/pnpm/action-setup
        with:
          run_install: false               # we’ll run it explicitly

      # 3 · Install Node *after* pnpm so caching works
      - uses: actions/setup-node@v4
        with:
          node-version: '20'               # any LTS you like
          cache: 'pnpm'                    # will now find pnpm just fine

      # 4 · Install deps & build
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build                # Vite outputs to dist/

      # 5 · Upload & deploy to Pages
      - uses: actions/upload-pages-artifact@v3
        with: { path: dist }
      - uses: actions/deploy-pages@v4
        id: deploy
